/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type SchnorrSignStruct = {
  signature: PromiseOrValue<BigNumberish>;
  owner: PromiseOrValue<string>;
  nonce: PromiseOrValue<string>;
};

export type SchnorrSignStructOutput = [BigNumber, string, string] & {
  signature: BigNumber;
  owner: string;
  nonce: string;
};

export interface DeusBridgeInterface extends utils.Interface {
  functions: {
    "ETH_APP_ID()": FunctionFragment;
    "claim(address,uint256,uint256,uint256,uint256,uint256,bytes,(uint256,address,address)[])": FunctionFragment;
    "claimedTxs(uint256,uint256)": FunctionFragment;
    "collectedFees(uint256)": FunctionFragment;
    "deposit(uint256,uint256,uint256)": FunctionFragment;
    "depositFor(address,uint256,uint256,uint256)": FunctionFragment;
    "destChain()": FunctionFragment;
    "emergencyWithdrawERC20Tokens(address,address,uint256)": FunctionFragment;
    "emergencyWithdrawETH(address,uint256)": FunctionFragment;
    "getExecutingChainID()": FunctionFragment;
    "getTransaction(uint256)": FunctionFragment;
    "getUserClaimedTxs(address,uint256)": FunctionFragment;
    "getUserDepositedTxs(address,uint256)": FunctionFragment;
    "getUserTxs(address,uint256,uint256,uint256)": FunctionFragment;
    "initialize(uint256,uint8,address,address)": FunctionFragment;
    "lastTxId()": FunctionFragment;
    "minReqSigs()": FunctionFragment;
    "muonContract()": FunctionFragment;
    "network()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingTxs(uint256,uint256[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "scale()": FunctionFragment;
    "setDestChain(uint256)": FunctionFragment;
    "setEthAppId(uint8)": FunctionFragment;
    "setFee(uint256,uint256)": FunctionFragment;
    "setMinReqSigs(uint256)": FunctionFragment;
    "setMuonContract(address)": FunctionFragment;
    "setNetworkID(uint256)": FunctionFragment;
    "setSideContract(uint256,address)": FunctionFragment;
    "setToken(uint256,address)": FunctionFragment;
    "sideContracts(uint256)": FunctionFragment;
    "tokenFees(uint256)": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpase()": FunctionFragment;
    "withdrawFee(uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ETH_APP_ID"
      | "claim"
      | "claimedTxs"
      | "collectedFees"
      | "deposit"
      | "depositFor"
      | "destChain"
      | "emergencyWithdrawERC20Tokens"
      | "emergencyWithdrawETH"
      | "getExecutingChainID"
      | "getTransaction"
      | "getUserClaimedTxs"
      | "getUserDepositedTxs"
      | "getUserTxs"
      | "initialize"
      | "lastTxId"
      | "minReqSigs"
      | "muonContract"
      | "network"
      | "owner"
      | "pause"
      | "paused"
      | "pendingTxs"
      | "renounceOwnership"
      | "scale"
      | "setDestChain"
      | "setEthAppId"
      | "setFee"
      | "setMinReqSigs"
      | "setMuonContract"
      | "setNetworkID"
      | "setSideContract"
      | "setToken"
      | "sideContracts"
      | "tokenFees"
      | "tokens"
      | "transferOwnership"
      | "unpase"
      | "withdrawFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ETH_APP_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      SchnorrSignStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedTxs",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFor",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "destChain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawERC20Tokens",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawETH",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutingChainID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClaimedTxs",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDepositedTxs",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTxs",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "lastTxId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minReqSigs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "muonContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "network", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTxs",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "scale", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDestChain",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setEthAppId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinReqSigs",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMuonContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setNetworkID",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSideContract",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sideContracts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenFees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "ETH_APP_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimedTxs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destChain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawERC20Tokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutingChainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClaimedTxs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDepositedTxs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserTxs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastTxId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minReqSigs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "muonContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "network", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingTxs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDestChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEthAppId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinReqSigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMuonContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNetworkID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSideContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sideContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;

  events: {
    "Claim(address,uint256,uint256,uint256,uint256)": EventFragment;
    "Deposit(address,uint256,uint256,uint256,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface ClaimEventObject {
  user: string;
  tokenId: BigNumber;
  amount: BigNumber;
  fromChain: BigNumber;
  txId: BigNumber;
}
export type ClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  ClaimEventObject
>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface DepositEventObject {
  user: string;
  tokenId: BigNumber;
  amount: BigNumber;
  toChain: BigNumber;
  txId: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface DeusBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeusBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ETH_APP_ID(overrides?: CallOverrides): Promise<[number]>;

    claim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      fromChain: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      txId: PromiseOrValue<BigNumberish>,
      _reqId: PromiseOrValue<BytesLike>,
      sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimedTxs(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    collectedFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositFor(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    destChain(overrides?: CallOverrides): Promise<[BigNumber]>;

    emergencyWithdrawERC20Tokens(
      tokenAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyWithdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getExecutingChainID(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTransaction(
      txId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ] & {
        txId: BigNumber;
        tokenId: BigNumber;
        amount: BigNumber;
        fromChain: BigNumber;
        toChain: BigNumber;
        user: string;
        txBlockNo: BigNumber;
        currentBlockNo: BigNumber;
      }
    >;

    getUserClaimedTxs(
      user: PromiseOrValue<string>,
      fromChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getUserDepositedTxs(
      user: PromiseOrValue<string>,
      toChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getUserTxs(
      user: PromiseOrValue<string>,
      chain: PromiseOrValue<BigNumberish>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[]]>;

    initialize(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      muon_: PromiseOrValue<string>,
      legacyDei_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    lastTxId(overrides?: CallOverrides): Promise<[BigNumber]>;

    minReqSigs(overrides?: CallOverrides): Promise<[BigNumber]>;

    muonContract(overrides?: CallOverrides): Promise<[string]>;

    network(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingTxs(
      fromChain: PromiseOrValue<BigNumberish>,
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[boolean[]] & { unclaimedIds: boolean[] }>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    scale(overrides?: CallOverrides): Promise<[BigNumber]>;

    setDestChain(
      chain: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setEthAppId(
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFee(
      tokenId: PromiseOrValue<BigNumberish>,
      fee_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinReqSigs(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMuonContract(
      muonContract_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNetworkID(
      network_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSideContract(
      network_: PromiseOrValue<BigNumberish>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sideContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    tokenFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpase(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFee(
      tokenId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  ETH_APP_ID(overrides?: CallOverrides): Promise<number>;

  claim(
    user: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    fromChain: PromiseOrValue<BigNumberish>,
    toChain: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    txId: PromiseOrValue<BigNumberish>,
    _reqId: PromiseOrValue<BytesLike>,
    sigs: SchnorrSignStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimedTxs(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  collectedFees(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    amount: PromiseOrValue<BigNumberish>,
    toChain: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositFor(
    user: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    toChain: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  destChain(overrides?: CallOverrides): Promise<BigNumber>;

  emergencyWithdrawERC20Tokens(
    tokenAddr: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyWithdrawETH(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getExecutingChainID(overrides?: CallOverrides): Promise<BigNumber>;

  getTransaction(
    txId_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber
    ] & {
      txId: BigNumber;
      tokenId: BigNumber;
      amount: BigNumber;
      fromChain: BigNumber;
      toChain: BigNumber;
      user: string;
      txBlockNo: BigNumber;
      currentBlockNo: BigNumber;
    }
  >;

  getUserClaimedTxs(
    user: PromiseOrValue<string>,
    fromChain: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getUserDepositedTxs(
    user: PromiseOrValue<string>,
    toChain: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getUserTxs(
    user: PromiseOrValue<string>,
    chain: PromiseOrValue<BigNumberish>,
    offset: PromiseOrValue<BigNumberish>,
    limit: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber[]]>;

  initialize(
    minReqSigs_: PromiseOrValue<BigNumberish>,
    ETH_APP_ID_: PromiseOrValue<BigNumberish>,
    muon_: PromiseOrValue<string>,
    legacyDei_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  lastTxId(overrides?: CallOverrides): Promise<BigNumber>;

  minReqSigs(overrides?: CallOverrides): Promise<BigNumber>;

  muonContract(overrides?: CallOverrides): Promise<string>;

  network(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingTxs(
    fromChain: PromiseOrValue<BigNumberish>,
    ids: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<boolean[]>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  scale(overrides?: CallOverrides): Promise<BigNumber>;

  setDestChain(
    chain: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setEthAppId(
    ETH_APP_ID_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFee(
    tokenId: PromiseOrValue<BigNumberish>,
    fee_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinReqSigs(
    minReqSigs_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMuonContract(
    muonContract_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNetworkID(
    network_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSideContract(
    network_: PromiseOrValue<BigNumberish>,
    address_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setToken(
    tokenId: PromiseOrValue<BigNumberish>,
    tokenAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sideContracts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  tokenFees(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpase(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFee(
    tokenId: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ETH_APP_ID(overrides?: CallOverrides): Promise<number>;

    claim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      fromChain: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      txId: PromiseOrValue<BigNumberish>,
      _reqId: PromiseOrValue<BytesLike>,
      sigs: SchnorrSignStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimedTxs(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    collectedFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFor(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    destChain(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyWithdrawERC20Tokens(
      tokenAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyWithdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getExecutingChainID(overrides?: CallOverrides): Promise<BigNumber>;

    getTransaction(
      txId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber
      ] & {
        txId: BigNumber;
        tokenId: BigNumber;
        amount: BigNumber;
        fromChain: BigNumber;
        toChain: BigNumber;
        user: string;
        txBlockNo: BigNumber;
        currentBlockNo: BigNumber;
      }
    >;

    getUserClaimedTxs(
      user: PromiseOrValue<string>,
      fromChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getUserDepositedTxs(
      user: PromiseOrValue<string>,
      toChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getUserTxs(
      user: PromiseOrValue<string>,
      chain: PromiseOrValue<BigNumberish>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[]]>;

    initialize(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      muon_: PromiseOrValue<string>,
      legacyDei_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    lastTxId(overrides?: CallOverrides): Promise<BigNumber>;

    minReqSigs(overrides?: CallOverrides): Promise<BigNumber>;

    muonContract(overrides?: CallOverrides): Promise<string>;

    network(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingTxs(
      fromChain: PromiseOrValue<BigNumberish>,
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<boolean[]>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    scale(overrides?: CallOverrides): Promise<BigNumber>;

    setDestChain(
      chain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setEthAppId(
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFee(
      tokenId: PromiseOrValue<BigNumberish>,
      fee_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinReqSigs(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMuonContract(
      muonContract_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setNetworkID(
      network_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSideContract(
      network_: PromiseOrValue<BigNumberish>,
      address_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sideContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    tokenFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpase(overrides?: CallOverrides): Promise<void>;

    withdrawFee(
      tokenId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Claim(address,uint256,uint256,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      tokenId?: null,
      amount?: null,
      fromChain?: PromiseOrValue<BigNumberish> | null,
      txId?: null
    ): ClaimEventFilter;
    Claim(
      user?: PromiseOrValue<string> | null,
      tokenId?: null,
      amount?: null,
      fromChain?: PromiseOrValue<BigNumberish> | null,
      txId?: null
    ): ClaimEventFilter;

    "Deposit(address,uint256,uint256,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      tokenId?: null,
      amount?: null,
      toChain?: PromiseOrValue<BigNumberish> | null,
      txId?: null
    ): DepositEventFilter;
    Deposit(
      user?: PromiseOrValue<string> | null,
      tokenId?: null,
      amount?: null,
      toChain?: PromiseOrValue<BigNumberish> | null,
      txId?: null
    ): DepositEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    ETH_APP_ID(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      fromChain: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      txId: PromiseOrValue<BigNumberish>,
      _reqId: PromiseOrValue<BytesLike>,
      sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimedTxs(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectedFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositFor(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    destChain(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyWithdrawERC20Tokens(
      tokenAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyWithdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getExecutingChainID(overrides?: CallOverrides): Promise<BigNumber>;

    getTransaction(
      txId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserClaimedTxs(
      user: PromiseOrValue<string>,
      fromChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserDepositedTxs(
      user: PromiseOrValue<string>,
      toChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserTxs(
      user: PromiseOrValue<string>,
      chain: PromiseOrValue<BigNumberish>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      muon_: PromiseOrValue<string>,
      legacyDei_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    lastTxId(overrides?: CallOverrides): Promise<BigNumber>;

    minReqSigs(overrides?: CallOverrides): Promise<BigNumber>;

    muonContract(overrides?: CallOverrides): Promise<BigNumber>;

    network(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingTxs(
      fromChain: PromiseOrValue<BigNumberish>,
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    scale(overrides?: CallOverrides): Promise<BigNumber>;

    setDestChain(
      chain: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setEthAppId(
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFee(
      tokenId: PromiseOrValue<BigNumberish>,
      fee_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinReqSigs(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMuonContract(
      muonContract_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNetworkID(
      network_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSideContract(
      network_: PromiseOrValue<BigNumberish>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sideContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpase(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFee(
      tokenId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ETH_APP_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      fromChain: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      txId: PromiseOrValue<BigNumberish>,
      _reqId: PromiseOrValue<BytesLike>,
      sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimedTxs(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectedFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositFor(
      user: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      toChain: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    destChain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    emergencyWithdrawERC20Tokens(
      tokenAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyWithdrawETH(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getExecutingChainID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransaction(
      txId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserClaimedTxs(
      user: PromiseOrValue<string>,
      fromChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserDepositedTxs(
      user: PromiseOrValue<string>,
      toChain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserTxs(
      user: PromiseOrValue<string>,
      chain: PromiseOrValue<BigNumberish>,
      offset: PromiseOrValue<BigNumberish>,
      limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      muon_: PromiseOrValue<string>,
      legacyDei_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    lastTxId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minReqSigs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    muonContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    network(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingTxs(
      fromChain: PromiseOrValue<BigNumberish>,
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    scale(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDestChain(
      chain: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setEthAppId(
      ETH_APP_ID_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFee(
      tokenId: PromiseOrValue<BigNumberish>,
      fee_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinReqSigs(
      minReqSigs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMuonContract(
      muonContract_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNetworkID(
      network_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSideContract(
      network_: PromiseOrValue<BigNumberish>,
      address_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setToken(
      tokenId: PromiseOrValue<BigNumberish>,
      tokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sideContracts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenFees(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpase(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFee(
      tokenId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
