/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type SchnorrSignStruct = {
  signature: PromiseOrValue<BigNumberish>;
  owner: PromiseOrValue<string>;
  nonce: PromiseOrValue<string>;
};

export type SchnorrSignStructOutput = [BigNumber, string, string] & {
  signature: BigNumber;
  owner: string;
  nonce: string;
};

export interface IMuonV02Interface extends utils.Interface {
  functions: {
    "verify(bytes,uint256,(uint256,address,address)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "verify"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      SchnorrSignStruct[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface IMuonV02 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMuonV02Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verify(
      reqId: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BigNumberish>,
      _sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  verify(
    reqId: PromiseOrValue<BytesLike>,
    hash: PromiseOrValue<BigNumberish>,
    _sigs: SchnorrSignStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    verify(
      reqId: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BigNumberish>,
      _sigs: SchnorrSignStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verify(
      reqId: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BigNumberish>,
      _sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verify(
      reqId: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BigNumberish>,
      _sigs: SchnorrSignStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
