/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDeusBridge } from "./IDeusBridge";
export type { IERC20 } from "./IERC20";
export type { IMuonV02 } from "./IMuonV02";
