/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMuonV02,
  IMuonV02Interface,
} from "../../../contracts/interfaces/IMuonV02";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "reqId",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "hash",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "signature",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "nonce",
            type: "address",
          },
        ],
        internalType: "struct SchnorrSign[]",
        name: "_sigs",
        type: "tuple[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMuonV02__factory {
  static readonly abi = _abi;
  static createInterface(): IMuonV02Interface {
    return new utils.Interface(_abi) as IMuonV02Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMuonV02 {
    return new Contract(address, _abi, signerOrProvider) as IMuonV02;
  }
}
